### ISSUE TITLE
PDFs of Schematics

### ISSUE THREAD

**Issue by lwbantoto** [SoonerRobotics/MercuryEE2019-2020#1]
Hey @j-exinia can you upload PDFs of each schematic?

**Comment by j-exinia** [comment]
Will do, working on getting them in right now.

**Comment by lwbantoto** [comment]
Thanks

**Comment by j-exinia** [comment]
I got the PDF for the breakout board. I'm working on trying to get the part for the power modules because it was done on a different computer and the libraries weren't uploaded with the project.

**Comment by lwbantoto** [comment]
Sounds good. Will review the breakout board schematic and layout for now. Feel free to close this issue when the other PDF is uploaded

**Comment by j-exinia** [comment]
Ok the other PDF is uploaded
